### PR TITLE
Delete hsdis folder

### PR DESCRIPTION
**Pull request by andrew-m-leonard**
Signed-off-by: andrew-m-leonard <andrew_m_leonard@uk.ibm.com>

### CODE REVIEW

**Comment by andrew-m-leonard** [comment]
jenkins compile xlinux

**Comment by andrew-m-leonard** [comment]
jenkins compilex xLinux

**Comment by pshipton** [comment]
jenkins compile xlinux jdk12

**Review by pshipton — APPROVED** [review]

**Comment by pshipton** [comment]
@andrew-m-leonard merged. I expect we need the same change for the 0.15 release branch.

**Comment by pshipton** [comment]
Does jdk13 and jdk (head) need the same change?

**Comment by andrew-m-leonard** [comment]
Yes on todo list
https://github.ibm.com/runtimes/openjdk-contribution/issues/896

**Pull request merged**
