### PR TITLE
Add support for OpenSSL 1.0.1 at runtime

### PR DESCRIPTION
**Pull request by groeges**
Signed-off-by: Steve Groeger <GROEGES@uk.ibm.com>

### CODE REVIEW

**Comment by groeges** [comment]
jenkins compile xlinux,win

**Comment by groeges** [comment]
jenkins compile xlinux

**Comment by groeges** [comment]
jenkins compile xlinux

**Review by davehobbs — APPROVED** [review]
LGTM  subject to comments in https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/96/files

**Pull request merged**
